#
# SPDX-License-Identifier: Apache-2.0
#
repository:
  name: citizens-pulse
  description: A fully distributed citizens pulse platform for state/city councils - with Hyperledger Fabric
  archived: true
  private: false
